THEOplayer/documentation

- .github/workflows/deploy.yml
- .github/workflows/theoplayer-release.yml
Whenever THEOplayer pushes a new branch named `release/theoplayer-x.y.z`, we will automatically create a pull request for it using [the GitHub CLI](https://cli.github.com/manual/gh_pr_create).
Open questions:
* No, we should review the PR manually first.
* (We should probably add some proper CI first, so we don't break our website. 😅)
* I've created the @THEOplayer/documentation-reviewers team, and added them to CODEOWNERS. 2 members of the team will be auto-assigned to each pull request, and 1 approval is required to merge. [See the ruleset for details.](https://github.com/THEOplayer/documentation/rules/479513?ref=refs%2Fheads%2Fmain)
> Add CI for THEOplayer releases

- .github/workflows/deploy.yml
- .github/workflows/pr-preview.yml
- docusaurus.config.ts
Uses the [deploy-pr-preview](https://github.com/marketplace/actions/deploy-pr-preview) action to deploy to the `gh-pages` branch.
> Add CI for deploying pull request previews

- .github/workflows/update-submodules.yml
- .gitmodules
This adds a new workflow that will:
1. Create a new `update-submodules` branch (if it doesn't exist yet)
2. Update all submodules in the project
3. If the submodules have any relevant docs changes (i.e. changes to `CHANGELOG.md`, `doc/` or `docs/`):
1. Push a new commit to the `update-submodules` branch
2. Open a pull request (if non exists yet)
4. (Otherwise, it discards the update)
> Add CI to automatically update submodules nightly

- .gitmodules
This avoids pushing unreleased changelogs to the documentation website.
> Use master branch for React Native SDK and React Native UI

- .github/workflows/update-submodules.yml
- .gitmodules
As suggested in https://github.com/THEOplayer/react-native-theoplayer/pull/310#discussion_r1572148403, we will pin the v4 docs for the React Native SDK to an older version, so https://github.com/THEOplayer/react-native-theoplayer/pull/310 can clean up the React Native docs for v6 and beyond.
> Pin React Native docs for THEOplayer v4

- theoplayer/changelog.md
Current changelog on the website converted `:dash:` to 💨
> Fix unintended :dash: emoji

- theoads/getting-started/00-getting-started-web.mdx
In the next version of THEOplayer, THEOads customers will need to add a new flag to their player configuration. Document this new requirement.
> Document new `theoads` player configuration flag

- src/components/PlatformSelect/index.tsx
- src/contexts/lastPlatform.tsx
- src/theme/DocRoot/Layout/index.tsx
- src/util/platform.ts
When using the platform select dropdown, we currently always navigate to the start page of that SDK. This is annoying if you're already on a specific article, since now you have to manually find that same article for the newly selected SDK.
This PR improves this by trying to find a matching article based on the article's URL. We assume that our articles have a predictable URL structure, and that articles with similar URLs have similar content. Some examples:
* `/theoplayer/getting-started/sdks/web/migrating-to-theoplayer-8` matches with `/theoplayer/getting-started/sdks/android/migrating-to-theoplayer-8`
* `/theoplayer/connectors/web/comscore/getting-started` matches with `/theoplayer/connectors/android/comscore/getting-started`
* `/open-video-ui/web/guides/custom-ui` matches with …
> Navigate to matching page when switching platforms

- theoads/how-to-guides/scheduling-breaks.md
Update the schedule ad break how to guide to include the newly added `assetURI`.
> THEOads: update schedule ad break guide

- theoplayer/how-to-guides/android/millicast/getting-started.mdx
This PR updates the how-to guide for the new Millicast integrations on Android with information on how to provide additional configuration that is specific for Millicast streams.
> Add Millicast configuration on Android

- .github/workflows/pr-preview.yml
When deploying a pull request preview for a PR from an external contributor (such as #164), [the deploy job failed](https://github.com/THEOplayer/documentation/actions/runs/11974630234/job/33462866909) with the following error:
```
Pushing changes… (attempt 1 of 3)
/usr/bin/git push --porcelain ***github.com/THEOplayer/documentation.git github-pages-deploy-action/5p62z7u4e:gh-pages
remote: Permission to THEOplayer/documentation.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/THEOplayer/documentation.git/': The requested URL returned error: 403
```
I *think* this is an issue with the permissions of the default `GITHUB_TOKEN`? Let's see if it works better with an app token from our own friendly THEOplayer bot.
> Use app token for deploying PR previews

- theoplayer/how-to-guides/android/media3/getting-started.mdx
* We're now publishing the Media3 integration to releases, so we don't need to talk about the snapshots repository anymore.
* A lot of previously known limitations have now been partially or fully fixed.
> Update Media3 guide for THEOplayer 8.10

- theoplayer/how-to-guides/android/media3/getting-started.mdx
* We're planning to enable Media3 by default in 9.0. Document this ahead of time.
* We've added full support for the ABR, network, latency and caching APIs. Remove those from the known limitations.
* Media3 is now also a caching integration. Add a section to explain how to use this.
* We're renaming `Media3PlayerIntegration` to just `Media3Integration`.
* We're deprecating `Media3PlayerIntegration.SourceSelectCallback` in favor of setting `TypedSource.playbackPipeline`. Update the examples to use the new API.
Supersedes #230.
> Update Media3 guide for THEOplayer 8.13

- .github/workflows/pr-build.yml
- .github/workflows/pr-preview.yml
At the moment, we can't deploy pull request previews for forks [due to a limitation of rossjrw/pr-preview-action](https://github.com/rossjrw/pr-preview-action/pull/6) (and also because of security considerations). However, we still want to run *some* checks on such PRs, so we can detect common problems like Markdown errors or broken links.
This adds a separate workflow specific for PRs from forks, which only builds the website without deploying it. The deploy preview workflow is now limited to run only on our own non-fork PRs.
> Add separate workflow to build PRs from forks

- millicast/webhooks/feeds-webhooks.md
We recently added `sourceId` and optionally `simulcastId` key-value pairs to be reflected in the feedhooks payload.
Here is a ticket that explains the behavior - https://jira.dolby.net/jira/browse/DIOS-8371
Here is a confluence page with the tests performed:
https://confluence.dolby.net/kb/x/jLdZL
> update feedhook docs to include sourceId and simulcastId

- millicast/webhooks/feeds-webhooks.md
We needed to revert the sourceId/simulcastId changes for 3.0.0 and will release them not long away in 3.0.1 
For now I am reverting the changes made for them in the docs, but we also forgot to add the priority optional field which I have added in this doc update.
> Update feeds-webhooks.md add priority and reverting sourceId/simulcastId in feed:hooks

- src/util/platform.ts
This PR adds logic for being able to switch between Web, iOS, Android and React Native regarding the Millicast documentation.
In order for this PR to be merged, [the corresponding PR](https://github.com/THEOplayer/react-native-theoplayer/pull/526) should land first.
> Support for switch between platforms for Millicast on React Native

- theoplayer/faq/81-supported-platforms.md
Apparently HTML headings don't show up in the table of contents, so you *have* to use Markdown headings [(see docs)](https://docusaurus.io/docs/markdown-features/toc#customizing-table-of-contents-generation). It's always a bit awkward to mix HTML and Markdown, but at least it works. 😛
I also moved "version" and "DRM" into the `<thead>`. (Yes, you're allowed to have two `<tr>`s inside a single `<thead>`. 😉)
> Add headings to supported platforms page for better ToC

- millicast/broadcast/software-encoders/ffmpeg.mdx
- theolive/contribution/software-encoders/ffmpeg.md
Update the FFmpeg guides to mention about not using `-re` flag if the input is a live stream.
> Update FFmpeg guides

- theoplayer/api-reference/roku.md
NOTE: needs to wait for the 9.8 release to be merged.
Added in the documentation for the theolive configuration (and added a missing licenseUrl property in the process).
> Adding API information for THEOlive configuration

- theolive/playback/flutter/_category_.json
- theolive/playback/ios/00-getting-started.mdx
- theolive/playback/ios/_category_.json
- theolive/playback/react-native/00-getting-started.mdx
- theolive/playback/react-native/_category_.json
- theolive/playback/react-native/token-based-security.mdx
- theolive/playback/roku/_category_.json
- theolive/playback/roku/token-based-security.mdx
Adding basic docs for how to configure JWT tokens for secured THEOlive channel playback.
Adding some reviewers here
@turbidwater can you sanity check my Roku guide
@tvanlaerhoven can you sanity check my React Native guide
@cTopher let's look at who can
- Update the main token based security page, cause that still mentions channel aliases etc, and we'll need to remove the player instructions there and link through to these but maybe there's more changes to make backend and channel wise
- Extend the iOS and React Native base getting started's a bit and what we want to include there, I made it very barebones to begin with just so we can have the JWT previews up already for sharing
> Token based security for THEOlive on React Native and Roku

- docusaurus.config.ts
Should make things look a little bit nicer, without needing to put a Markdown frontmatter everywhere.
> Add default description for changelog pages

- .gitmodules
- sidebarsTheoplayer.ts
* [react-native-theoplayer-ui](https://github.com/THEOplayer/react-native-theoplayer-ui) renamed their main branch from `master` to `main` in https://github.com/THEOplayer/react-native-theoplayer-ui/commit/c2e3475e106c8414acfec2134deab567cd18c254.
* The [Conviva-VerizonMedia connector for iOS got removed for 10.0](https://github.com/THEOplayer/iOS-Connector/commit/5c2d9a4b8bde920efeebebc1ecbfba91e5539ec3), so also remove it from the docs.
> Fix documentation from submodules
