- docusaurus.config.ts
- package-lock.json
- package.json
- src/components/CodeInput/index.tsx
- theoplayer/static/theoplayer/v6/examples/basic/demo.html
See https://github.com/THEOplayer/web-ui/pull/54
> Migrate examples from Open Video UI for Web

- .github/workflows/deploy.yml
- docusaurus.config.ts
> Deploy to production

- package-lock.json
- package.json
See https://github.com/THEOplayer/web-ui/pull/57
> Add guide on making custom components with Web UI

- package-lock.json
- package.json
See [changelog](https://docusaurus.io/changelog/3.2.0)
> Update to Docusaurus 3.2.0

- theoplayer/how-to-guides/12-license/00-introduction.md
- theoplayer_versioned_docs/version-v4/how-to-guides/12-license/00-introduction.md
- theoplayer_versioned_docs/version-v6/how-to-guides/12-license/00-introduction.md
Add explanation on how to protect the license.
> Update license guide

- sidebarsTheoplayer.ts
See also https://github.com/THEOplayer/android-connector/pull/19
> Add links to API docs for Android connectors

- .github/workflows/update-submodules.yml
- docusaurus.config.ts
- sidebarsTheoplayer.ts
See [android-connector on GitHub](https://github.com/THEOplayer/android-connector/tree/master/connectors/yospace).
> Yospace Connector for Android

- package-lock.json
- package.json
See [blog post](https://docusaurus.io/blog/releases/3.4).
> Update to Docusaurus 3.4.0

- package-lock.json
- package.json
- src/components/PlatformSelect/index.tsx
- src/components/SidebarDocCardList/index.tsx
- src/components/SubcategoryDocCardList/index.tsx
- src/contexts/lastPlatform.tsx
- src/theme/DocCard/index.tsx
- src/theme/DocCardList/index.tsx
- src/theme/DocRoot/Layout/index.tsx
See [release notes](https://docusaurus.io/blog/releases/3.5).
> Upgrade to Docusaurus 3.5.2

- theoplayer/how-to-guides/android/media3/getting-started.mdx
- theoplayer/how-to-guides/android/millicast/getting-started.mdx
Fixing some small mistakes that slipped through the cracks... 😅
> Fix Android guides for Millicast and Media3

- theoplayer/how-to-guides/web/millicast/getting-started.mdx
This PR updates the how-to guide for the new Millicast integrations on Web with information on how to provide additional configuration that is specific for Millicast streams.
> Add Millicast configuration on web

- theoads/getting-started/00-getting-started-android.mdx
Fixes incorrect dependency link
> Fix incorrect dependency

- .github/workflows/lint.yml
- docusaurus.config.ts
- eslint.config.mjs
- package-lock.json
- package.json
- src/components/Select/index.tsx
- src/components/SidebarDocCardList/index.tsx
- src/contexts/lastPlatform.tsx
- src/contexts/reactAriaRouterProvider.tsx
- src/theme/DocCard/index.tsx
- src/util/platform.ts
- theoplayer/how-to-guides/android/media3/getting-started.mdx
Also check for formatting and lint issues on CI, so I (hopefully) don't have to make more PRs like #166. 😛
> Add ESLint

- theoads/api/ads-client.swagger.json
- theoads/api/signaling/sidebar.ts
- theoads/how-to-guides/create-backdrop-layout.md
- theoads/how-to-guides/scheduling-breaks.md
- theoads/how-to-guides/scheduling-overlays.md
- theoads/how-to-guides/workflow-integration.md
Updated API with overlay request.
Updated how-to-guides with Overlay scheduling.
> Theoads api docs

- theoplayer/how-to-guides/04-drm/02-axinom.md
From request by Axinom, updating the URL we refer to in our resources link in our DRM docs.
> Update Axinom URL

- theoplayer/how-to-guides/ios/millicast/getting-started.mdx
Add docs for options configuration and how to handle background playback
> iOS Millicast config and bg docs

- theoplayer/faq/72-what-are-the-uplynk-challenges.md
- theoplayer/how-to-guides/01-ads/11-how-to-subscribe-to-ad-events.md
- theoplayer/how-to-guides/web/uplynk/00-introduction.mdx
- theoplayer/how-to-guides/web/uplynk/01-preplay.md
- theoplayer/how-to-guides/web/uplynk/02-ads.md
- theoplayer/how-to-guides/web/uplynk/03-ping.md
- theoplayer/how-to-guides/web/uplynk/04-configuration.md
- theoplayer/how-to-guides/web/uplynk/05-interface.md
- theoplayer/how-to-guides/web/uplynk/_category_.json
This PR contains the updated documentation for the Verizon Media integration, which has been renamed to Uplynk.
> Uplynk web docs

- theoplayer/getting-started/01-sdks/02-android/01-features.md
- theoplayer/how-to-guides/01-ads/08-google-dai.md
- theoplayer/how-to-guides/01-ads/10-google-ima.md
- theoplayer/how-to-guides/01-ads/12-mediatailor.md
- theoplayer/how-to-guides/android/millicast/getting-started.mdx
This documents the upcoming automatic integrations feature for the Android SDK. See "Android SDK > Getting Started > Android Feature Integrations" for the new content.
I've also updated and cleaned up some of our existing integration docs while I was at it. 😛
> Automatic integrations for Android

- theolive/guides/Ingesting/ffmpeg.md
Add `FFmpeg` section for THEOLive
> Add FFmpeg for THEOLive

- millicast/software-encoders/obs/obs-enhanced-broadcasting-multitrack-video.mdx
An update to our docs to better align with naming conventions per the request of OBS:
https://github.com/obsproject/obs-studio/pull/11509
> updates to enahnced broadcasting title and description for OBS PR

- src/css/custom.css
> Update title CSS broken for small screens

- theolive/platform/authorization.mdx
- theolive/platform/manage-team.mdx
- theolive/platform/scheduler.mdx
- theolive/platform/viewer-insights.mdx
Made changes to manage team, authorization, viewer insights, and scheduler pages. Cleaned up language and added additional info
> Updates to platform pages

- docusaurus.config.ts
- Add the click to send button for REST APIs in Millicast and THEOlive sections.
> Add click to send button for REST APIs for Millicast and Live

- theoplayer/faq/81-supported-platforms.md
Add list of supported platfroms for THEOplayer from this [page](https://www.theoplayer.com/platform-support).
> Add list of supported platform for player

- .github/workflows/deploy-staging.yml
- .github/workflows/deploy.yml
> Add workflow to deploy to staging

- redirectsTHEOPlayer.json
- theoplayer/how-to-guides/04-drm/02-axinom.md
- theoplayer/how-to-guides/04-drm/04-ezdrm.md
- theoplayer/how-to-guides/04-drm/07-microsoft-azure.md
- theoplayer/how-to-guides/04-drm/09-verimatrix-multirights.md
- theoplayer/how-to-guides/04-drm/11-vualto-vudrm.md
- theoplayer/how-to-guides/04-drm/13-xstream.md
- theoplayer/how-to-guides/04-drm/15-doverunner.md
> Updated PallyCon to DoveRunner branding
